name: Deploy Spring Boot App

on:
  push:
    branches:
      - main  # or your specific branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: /home/ubuntu/deployment/main
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
#
#      - name: Restart Spring Boot App
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{secrets.REMOTE_HOST}}
#          username: ${{secrets.REMOTE_USERNAME}}
#          key: ${{secrets.REMOTE_SSH_KEY}}
#          script: |
#            pkill -f your-app-name.jar
#            nohup java -jar /path/on/remote/server/your-app-name.jar > app.log 2>&1 &
