name: Deploy Spring Boot App
on:
  push:
    branches:
      - main  # or your specific branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploying springboot app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ~/deployments
            rm -rf main.bak
            cp -R main main.bak
            rm -rf main
            git clone git@github.com:mythical-elephant/onikai-backend.git main
            cd main
            npm install
            npm run build-sass
            echo -e "spring.datasource.url=${{secrets.SPRING_DATASOURCE_URL}}\n\
            spring.datasource.username=${{secrets.SPRING_DATASOURCE_USERNAME}}\n\
            spring.datasource.password=${{secrets.SPRING_DATASOURCE_PASSWORD}}\n\
            onikai.jwt.secret=${{secrets.ONIKAI_JWT_SECRET}}" > src/main/resources/application-secrets.properties
            bash mvnw package
            systemctl daemon-reload
            systemctl restart onikai-spring-prod.service
            
