name: Deploy Spring Boot App
on:
  push:
    branches:
      - main  # or your specific branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: Restart Spring Boot App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd ~/deployments
            rm -rf main.bak
            cd main
            git pull
            echo -e "spring.datasource.url=${{secrets.SPRING_DATASOURCE_URL}}\n \
            spring.datasource.username=${{secrets.SPRING_DATASOURCE_USERNAME}}\n \
            spring.datasource.password=${{secrets.SPRING_DATASOURCE_PASSWORD}}\n \
            onikai.jwt.secret=${{secrets.ONIKAI_JWT_SECRET}}" > src/main/resources/application-secrets.properties
            bash mvnw compile
            
            # pkill -f your-app-name.jar
            # nohup java -jar /path/on/remote/server/your-app-name.jar > app.log 2>&1 &
                # - name: Set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'adopt'

      # - name: Build with Maven
      #   run: mvn clean install

      # - name: Copy folder content recursively to remote
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: .
      #     remote: /home/ubuntu/deployment/main
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.PASSWORD }}
